### ISSUE TITLE
Needs new maintainer

### ISSUE THREAD

**Issue by isuruf** [conda-forge/magma-feedstock#15]
### Comment:

I don't want to maintain this feedstock anymore.

@conda-forge/pytorch-cpu, @IvanYashchuk

**Comment by hmaarrfk** [comment]
would you be willing to help answer a few questions;

The answer may be "I don't know, just try" but I'm just trying to be thorough.


1. Why can't we build `sm_30` and `sm_35`? It would help avoid us creating a new variable "ALL" that seems to only build `sm_37` and above.
2. Why are we patching out thread queue so heavily. Just commenting out "throwing" an exception seems scary.
3. Why do we need to export MAGMA_Z_INF and MAGMA_Z_NAN, the other definitions seem to have been deleted.

Thats about all the questions I have for now. I can ask these in a PR if you prefer

**Comment by isuruf** [comment]
> Why can't we build sm_30 and sm_35? It would help avoid us creating a new variable "ALL" that seems to only build sm_37 and above.

Usually, magma releases were behind a bit, so we needed to add some `sm` values. If magma is up-to-date with the arches that we compile for in pytorch, then we can drop that patch and set `GPU_TARGET`

> Why are we patching out thread queue so heavily. Just commenting out "throwing" an exception seems scary.

Can't remember

> Why do we need to export MAGMA_Z_INF and MAGMA_Z_NAN, the other definitions seem to have been deleted.

For windows DLLs. That's how creating windows DLLs work. `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` exports functions correctly, but it doesn't work for global data correctly.

**Comment by isuruf** [comment]
Btw, some of the patches were taken from [pytorch ](https://github.com/pytorch/builder/tree/main/magma/package_files)
