### ISSUE TITLE
CUDA 12.0 build on windows depends on `cuda-cudart >=12.1.105`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/magma-feedstock#41]
This [dependency](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Flibmagma_sparse-2.7.2-h82b23e0_2.conda#dependencies) then [forces](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Fcuda-cudart-12.1.105-h63175ca_0.conda#dependencies) `cuda-version >=12.1,<12.2.0a0`, which is not compatible with regular CUDA 12.0 compilation.

This then leads to failure in https://github.com/conda-forge/kaldi-feedstock/pull/47 (for linux it works because there are older libmagma_sparse builds that pull in cuda-cudart 12.0)

There was some discussion about this in #39, but nothing that seemed like explicitly choosing 12.1 components in the 12.0 build.

@conda-forge/magma CC @jakirkham

**Comment by jakirkham** [comment]
Think `cuda-version {{ cuda_compiler_version }}` needs to be added to `requirements/host` of all packages to ensure the same CUDA version is used in `requirements/build` as `requirements/host`

It was added here:

https://github.com/conda-forge/magma-feedstock/blob/509c0dcf2b395f27f255f465b183af5fe2656b5f/recipe/meta.yaml#L126

However sections like this are missing it:

https://github.com/conda-forge/magma-feedstock/blob/509c0dcf2b395f27f255f465b183af5fe2656b5f/recipe/meta.yaml#L149-L155

This affects things like `run_exports` that packages add, which is likely what is happening with `cuda-cudart` in this case
